clean:
	rm -fv *.log
	rm -fv *.aux
	rm -fv *.toc

cleanpdf:
	rm -fv *.log
	rm -fv *.aux
	rm -fv *.toc
	rm -fv *.pdf


tar: 
	tar czvf ../augustNICS.tar.gz ../august/*.tex ../august/*.pdf

backup: 
	tar czvf ../augustNICS.tar.gz ../august/*.tex ../august/*.pdf
