clean:
	rm -fv *.log
	rm -fv *.aux
	rm -fv *.toc

cleanpdf:
	rm -fv *.log
	rm -fv *.aux
	rm -fv *.toc
	rm -fv *.pdf


tar: 
	tar czvf ../octoberNICS.tar.gz ../october/*.tex ../october/*.pdf

backup: tar
