clean:
	rm -fv *.log
	rm -fv *.aux
	rm -fv *.toc

cleanpdf:
	rm -fv *.log
	rm -fv *.aux
	rm -fv *.toc
	rm -fv *.pdf


tar: 
	tar czvf ../septemberNICS.tar.gz ../sep/*.tex ../sep/*.pdf

backup: 
	tar czvf ../septemberNICS.tar.gz ../sep/*.tex ../sep/*.pdf
